# Add 'test' label to any change to *.spec.js files within the source directory
test:
  - src/api/**/*.test.js

# Add 'api' label to any new or updated files within the project
api:
  - src/api/*

# Add 'actions' label to any new or updated GitHub action workflow
actions:
  - .github/**/*.yml
